import React from "react";
import MainPage from "../components/Home/MainPage";
import Head from "next/head";
export default function Home() {
  return (
    <>
      <Head>
        <title>Harsh Jha</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainPage />;
    </>
  );
}
