import React from "react";
import MainPage from "../components/Home/MainPage";
import Head from "next/head";
export default function Home() {
  return (
    <>
      <Head>
        <title>Harsh Jha</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🐤</text></svg>"
        ></link>
      </Head>
      <MainPage />;
    </>
  );
}
